CORNER_POS:
  # limits of the arena in real life, in m
  ARENA:
    xmin: 0
    xmax: 4.10
    ymin: -1.60
    ymax: 1.70
  # corners of the arena in the video, in px
  VIDEO:
    TOP_LEFT: [550, 115] # corner at (xmin, ymax)
    TOP_RIGHT: [1480, 135] # corner at (xmax, ymax)
    BOTTOM_LEFT: [390, 928] # corner at (xmin, ymin)
    BOTTOM_RIGHT: [1685, 907] # corner at (xmax, ymin)

FUSION_PARAMS:
  THRESHOLD: 60
  
# BACKGROUND_IMG: "./test_data/background.png"

# Add a logo if you like
LOGO: 
  FILE: "./examples/not_KTH_logo.png" # Choose "" (empty string) for no logo
  SIZE: [120, 120] # Size of the logo in pixels
  OFFSET: [20, 20] # Offset of the logo in pixels, relative to the top right corner 
