# Add the positions (px) of the corners of the arena in the video
CORNER_POS:
  TOP_LEFT: 
    px: [550, 115]
  TOP_RIGHT:
    px: [1480, 135]
  BOTTOM_LEFT:
    px: [390, 928]
  BOTTOM_RIGHT: 
    px: [1685, 907]

FUSION_PARAMS:
  THRESHOLD: 60
  
# BACKGROUND_IMG: "./test_data/background.png"

# Add a logo if you like
LOGO: 
  FILE: "./examples/KTH_logo.png" # Choose "" (empty string) for no logo
  SIZE: [120, 120] # Size of the logo in pixels
  OFFSET: [20, 20] # Offset of the logo in pixels, relative to the top right corner 
